#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD$

PACKAGE=runtime
CONFGROUPS=	CONFS RCD
CONFS=	sysctl.conf
RCD=		sysctl
RCDDIR=	/etc/rc.d
RCDMODE=	${BINMODE}
PROG=	sysctl
WARNS?=	3
MAN=	sysctl.8

.include <bsd.prog.mk>
